# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html
# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Force software rendering for QtWebEngine. This is needed for
# QtWebEngine to work with Nouveau drivers.
# Type: Bool
c.downloads.position = 'bottom'
c.qt.force_software_rendering = True
c.qt.highdpi = True
c.auto_save.session = True
c.scrolling.smooth = False
c.url.default_page = '~/.startpage.html'
c.url.searchengines = {'DEFAULT': 'https://www.google.com/search?q={}', 
								'd': 'https://duckduckgo.com/?q={}', 
								'aw': 'https://wiki.archlinux.org/?search={}'}
c.url.start_pages = '~/.startpage.html'
# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

c.fonts.completion.entry = '10pt Iosevka'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 10pt Iosevka'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt Iosevka'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt Iosevka'

# Font used for the hints.
# Type: Font
c.fonts.hints = '10pt Iosevka'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt Iosevka'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt Iosevka'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '9pt Iosevka'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '9pt Iosevka'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10 pt Iosevka'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt Iosevka'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '9pt lucy tewi'



# Bindings for normal mode
config.bind(';M', 'hint links spawn gnome-mpv {hint-url}')
config.bind(';m', 'spawn gnome-mpv {url}',)

config.source('qutenyan/nyan.py')
config.source('nord-qutebrowser.py')