#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
bspc monitor -d 1 2 3 4 5

#gereral configs

bspc config border_width        2
bspc config window_gap          10

bspc config top_padding         5
bspc config bottom_padding      0
bspc config left_padding 	5
bspc config right_padding 	5

bspc config normal_border_color $color0
bspc config focused_border_color $color15
bspc config active_border_color $color1
bspc config presel_feedback_color $color3

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_frame_opacity         0.5
bspc config focused_frame_opacity        0.1

# desktop namesbspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Chromium sticky=off
bspc rule -a Dia state=floating 
bspc rule -a Ibus-extension-gtk3 state=floating 
bspc rule -a Godot state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Kupfer.py focus=on


